name: Rust Cross-Platform Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Linux dependencies
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libglib2.0-dev \
          libjavascriptcoregtk-4.1-dev \
          libsoup-3.0-dev \
          libwebkit2gtk-4.0-dev \
          pkg-config \
          build-essential \
          curl

    # macOS dependencies
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: brew install pkg-config gtk+3

    # Windows requires no extra deps for Tauri
    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri app
      working-directory: ./src-tauri
      run: cargo tauri build

    - name: Upload installers
      uses: actions/upload-artifact@v4
      with:
        name: tauri-installers-${{ matrix.os }}
        path: |
          ./src-tauri/target/release/bundle/msi/*
          ./src-tauri/target/release/bundle/deb/*
          ./src-tauri/target/release/bundle/dmg/*
