name: Rust Cross-Platform Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Install Tauri CLI
    - name: Install Tauri CLI
      run: cargo install tauri-cli

    # Build the app
    - name: Build Tauri app
      working-directory: ./src-tauri
      run: cargo tauri build

    # Upload installer artifacts
    - name: Upload installers
      uses: actions/upload-artifact@v4
      with:
        name: tauri-installers-${{ matrix.os }}
        path: |
          ./src-tauri/target/release/bundle/msi/*
          ./src-tauri/target/release/bundle/deb/*
          ./src-tauri/target/release/bundle/dmg/*
