name: Windows Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app (Windows)
        working-directory: ./src-tauri
        run: cargo tauri build

      - name: Upload Windows .msi
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: ./src-tauri/target/release/bundle/msi/*