name: Windows Build

on:
  push:
    paths:
      - 'src-tauri/tauri.conf.json'
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Check if version changed
        id: version
        shell: bash
        run: |
          if git diff HEAD^ HEAD -- src-tauri/tauri.conf.json | grep '"version"'; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip if version unchanged
        if: steps.version.outputs.version_changed == 'false' && !startsWith(github.ref, 'refs/tags/v')
        run: echo "No version change detected. Skipping build." && exit 0

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app (Windows)
        working-directory: ./src-tauri
        run: cargo tauri build

      - name: Upload Windows .msi
        uses: actions/upload-artifact@v4
        with:
          name: windows-msi
          path: ./src-tauri/target/release/bundle/msi/*